# -*- coding: utf-8 -*-
"""Practical_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPtghnl9vrdnkLMl85aJP0fgrOgSu-Cw
"""

!pip install ultralytics

from google.colab import files
uploaded = files.upload()

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

# Load YOLOv8 pre-trained model
model = YOLO("yolov8n.pt")   # 'n' = nano (fast & lightweight)

# Path to input image
image_path = "car3.jpg"    # CHANGE if filename is different

# Run detection
results = model(image_path)

# Read image using OpenCV
img = cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Get detections
for result in results:
    boxes = result.boxes
    for box in boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        conf = box.conf[0]
        cls = int(box.cls[0])
        label = model.names[cls]

        # Draw bounding box
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            img,
            f"{label} {conf:.2f}",
            (x1, y1 - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 0, 0),
            2
        )

# Display output
plt.figure(figsize=(10, 8))
plt.imshow(img)
plt.axis("off")
plt.show()