# -*- coding: utf-8 -*-
"""Practical_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q52132zDel0XedANsjy5N7lBeSO2LIpZ
"""

import numpy as np
import matplotlib.pyplot as plt

# Create 100x100 black image
image = np.zeros((100, 100))

# Add white square object
image[40:70, 40:70] = 255

# -------------------------------
# Step 2: Sliding Window Detection
# -------------------------------

window_size = 20
stride = 5
threshold = 200  # Brightness threshold

detections = []

for y in range(0, 100 - window_size + 1, stride):
    for x in range(0, 100 - window_size + 1, stride):

        # Extract window
        window = image[y:y+window_size, x:x+window_size]

        # Feature Extraction (Mean Intensity)
        feature = np.mean(window)

        # Simple Classification
        if feature > threshold:
            detections.append((x, y))

# -------------------------------
# Step 3: Visualize Results
# -------------------------------

plt.figure(figsize=(6,6))
plt.imshow(image, cmap='gray')

# Draw bounding boxes
for (x, y) in detections:
    rect = plt.Rectangle(
        (x, y),
        window_size,
        window_size,
        edgecolor='red',
        facecolor='none',
        linewidth=2
    )
    plt.gca().add_patch(rect)

plt.title("R-CNN Concept Demonstration")
plt.axis("off")
plt.show()

# -------------------------------
# Print Detected Coordinates
# -------------------------------

print("Detected Object Regions (Top-Left Coordinates):")
for d in detections:
    print("Object detected at:", d)

from google.colab import files
from PIL import Image
import io

print("\nNow upload your own image:")
uploaded = files.upload()

image_name = list(uploaded.keys())[0]
custom_image = Image.open(io.BytesIO(uploaded[image_name]))

# Convert to grayscale
custom_image = custom_image.convert("L")

# Resize for consistent processing
custom_image = custom_image.resize((200, 200))

custom_image = np.array(custom_image)

# Detection parameters (you can adjust)
window_size = 40
stride = 20
threshold = 180

detections_custom = []
height, width = custom_image.shape

for y in range(0, height - window_size + 1, stride):
    for x in range(0, width - window_size + 1, stride):

        window = custom_image[y:y+window_size, x:x+window_size]
        feature = np.mean(window)

        if feature > threshold:
            detections_custom.append((x, y))

# Show Results
plt.figure(figsize=(6,6))
plt.imshow(custom_image, cmap='gray')

for (x, y) in detections_custom:
    rect = plt.Rectangle(
        (x, y),
        window_size,
        window_size,
        edgecolor='red',
        facecolor='none',
        linewidth=2
    )
    plt.gca().add_patch(rect)

plt.title("R-CNN Concept - Custom Uploaded Image")
plt.axis("off")
plt.show()

print("Detected Regions in Uploaded Image:")
for d in detections_custom:
    print("Object detected at:", d)