# -*- coding: utf-8 -*-
"""Practical_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICX-0Y_-8b9uFstMt6wRQS4RKQP8XfhA
"""

!pip install opencv-contrib-python

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

# Load image (replace with your filename)
image_path = 'download.jpg'
img = cv2.imread(image_path)

# Convert BGR to RGB
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Create SIFT object
sift = cv2.SIFT_create()

# Detect keypoints and descriptors
keypoints, descriptors = sift.detectAndCompute(gray, None)

# Draw keypoints
sift_image = cv2.drawKeypoints(
    img_rgb,
    keypoints,
    None,
    flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS
)

# Display results
plt.figure(figsize=(10, 8))
plt.imshow(sift_image)
plt.title(f"SIFT Keypoints Detected: {len(keypoints)}")
plt.axis('off')
plt.show()

print("Descriptor shape:", descriptors.shape)