# -*- coding: utf-8 -*-
"""Practical_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDebALrNzoWPbbibevr_7_mXBe4mS-vk
"""

!pip install deepface
!pip install opencv-python

from google.colab import files
uploaded = files.upload()

from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt

images = ["happy.jpg", "fear.webp", "surprised.jpg", "face.webp", "angry.webp", "sad.jpg"]

for img_path in images:

    # Analyze emotion
    result = DeepFace.analyze(
        img_path=img_path,
        actions=['emotion'],
        enforce_detection=False
    )

    emotion = result[0]['dominant_emotion']

    print("\nImage:", img_path)
    print("Dominant Emotion:", emotion)
    print("Emotion Scores:", result[0]['emotion'])

    # Read and display image
    img = cv2.imread(img_path)

    if img is None:
        print("Image not found:", img_path)
        continue

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.imshow(img)
    plt.title("Detected Emotion: " + emotion)
    plt.axis("off")
    plt.show()