# -*- coding: utf-8 -*-
"""Practical_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mu8G510G9lEa4Tgf0KU1dfFKRjy-1o_9
"""

# ==========================================
# INSTALL LIBRARIES
# ==========================================
!pip -q install ultralytics deepface opencv-python-headless

# ==========================================
# IMPORTS
# ==========================================
from ultralytics import YOLO
from deepface import DeepFace
import cv2
import numpy as np
from google.colab import files
from google.colab.patches import cv2_imshow

# ==========================================
# LOAD YOLO OBJECT MODEL
# ==========================================
print("Loading YOLO object model...")
object_model = YOLO("yolov8n.pt")   # Official model (auto-downloads)

# ==========================================
# LOAD FACE DETECTOR (OpenCV built-in)
# ==========================================
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

print("Models loaded successfully!")

# ==========================================
# UPLOAD IMAGE
# ==========================================
print("Upload an image...")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

image = cv2.imread(image_path)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# ==========================================
# 1️⃣ OBJECT DETECTION
# ==========================================
results = object_model(image)

for r in results:
    boxes = r.boxes.xyxy.cpu().numpy()
    classes = r.boxes.cls.cpu().numpy()
    confs = r.boxes.conf.cpu().numpy()

    for box, cls, conf in zip(boxes, classes, confs):
        x1, y1, x2, y2 = map(int, box)
        label = object_model.names[int(cls)]

        cv2.rectangle(image, (x1,y1), (x2,y2), (255,0,0), 2)
        cv2.putText(image, f"{label} {conf:.2f}",
                    (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6, (255,0,0), 2)

# ==========================================
# 2️⃣ FACE DETECTION
# ==========================================
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x, y, w, h) in faces:
    face_crop = image[y:y+h, x:x+w]

    try:
        analysis = DeepFace.analyze(
            face_crop,
            actions=['gender'],
            enforce_detection=False
        )

        gender = analysis[0]['dominant_gender']
        confidence = max(analysis[0]['gender'].values())

        label_text = f"{gender} {confidence:.1f}%"

    except:
        label_text = "Gender: Unknown"

    # Draw face box
    cv2.rectangle(image, (x,y), (x+w,y+h), (0,255,0), 2)
    cv2.putText(image, label_text,
                (x, y-10),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7, (0,255,0), 2)

# ==========================================
# SHOW RESULT
# ==========================================
cv2_imshow(image)
cv2.waitKey(0)
cv2.destroyAllWindows()